--############################################# dbo.CUSTOMER #############################################
-- 16/10/2023 23:05 : add new Field [numFollow], [numFolderCourse], [numCourse] and [numQuiz]
